stages:
  - build
  - test

building:
  stage: build
  image: guia2612/lab3-2
  script:
    - apt install zlib1g
    - apt-get install zlib1g-dev
    - cd /boostinstall/boost_1_78_0
    - ./b2 --with-iostreams -a
    - cd /builds/dinf/cours/h22/igl601/guia2612/gitus-StartingPoint/
    - mkdir build
    - cd ./build/
    - printenv
    - cmake ..
    - make
    - echo "building..."
  artifacts:
    paths:
      - /builds/dinf/cours/h22/igl601/guia2612/gitus-StartingPoint/build/tests/gittests
      - /builds/dinf/cours/h22/igl601/guia2612/gitus-StartingPoint/build/gitus
    expire_in: 2 weeks
